# configs/test.yaml
# Ce fichier assemble la configuration COMPLÈTE pour un test.

defaults:
  - _self_

  # 1. On charge les "briques" de base de notre projet.
  #    Hydra les trouvera dans configs/data, configs/model, etc.
  - data: irm
  - model: vit_irm
  - trainer: gpu
  - callbacks: null # Pas de callbacks nécessaires pour le test

  # 2. EN DERNIER, on applique les paramètres spécifiques de notre expérience
  - optional experiment: mnist_inference