# configs/train.yaml

# La liste des 'defaults' est le menu de notre expérience.
# Hydra va les assembler dans cet ordre.
defaults:
  - _self_
  - data: mnist      # Charge la config des données MNIST
  - callbacks: default
  - model: vit_mnist   # Charge la config du modèle ViT
  - trainer: gpu     # Charge la config du Trainer pour GPU
  - logger: tensorboard

  # On peut aussi ajouter des configs pour les callbacks, les loggers, etc.
  # Mais gardons simple pour l'instant.

# On peut définir des paramètres globaux ici
seed: 42