services:
  app:
    image: modular-ai:1.0
    build: .
    container_name: modular-ai-app
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./configs:/app/configs
      - ./models:/app/models
      - ./out:/app/out
      - ./input:/app/input
      
    
    ports:
      - "6006:6006" # for tensorboard

    shm_size: '2gb'

    #comment the entire deploy section if you do not have a NVIDIA GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
    command: tail -f /dev/null