# configs/model/default.yaml

_target_: src.models.lit_model.LitModel

# Name of the model on hugging face
model_name: "google/vit-base-patch16-224-in21k"

# Automatically filled when discovering the dataset
num_classes: null 

# Default learning rate
lr: 0.0001