model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  
  dirpath: ${hydra:run.dir}/checkpoints

  filename: "{epoch}-{val_acc:.3f}"
  
  monitor: "val_acc"
  mode: "max"

  every_n_epochs: 1

  save_top_k: 1
  save_last: false


early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  
  monitor: "val_acc" 
  mode: "max"
  patience: 3
  verbose: true

test_evaluator:
  _target_: src.callbacks.evaluation.TestEvaluationCallback
  