# configs/predict.yaml

predict:

  # Folder containing the images used for inference
  input_dir: "/app/input"

  # Folder where the json will be created
  output_dir: "/app/out"


defaults:
  - _self_
  # Desactivation of hydra logging to prevent the creation of the outputs/ folder
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled


hydra:
  run:
    dir: .
  output_subdir: null

md : ??? # path to the model
file : null # path to a single file, if filled it will ignore the content of the input directory