# configs/train.yaml

defaults:
  - _self_
  - data: default
  - model: default      
  - trainer: gpu
  - logger: tensorboard
  - callbacks: default

category: "default" # sub category for the model


hydra:
  run:
    dir: models/${data.metadata_dir}/${category}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  

seed: 42

ds: ??? # dataset name, mandatory